### PR TITLE
Switch badge to CEID repo

### PR DESCRIPTION
**Pull request by e3bo**
Or maybe delete the badge altogether? I just thought it was cool.

### CODE REVIEW

**Comment by mvevans89** [comment]
I like the badge! Isn't it already on the CEID repo?

**Comment by mvevans89** [comment]
Also could you make one for the others? I couldn't figure out how it worked

**Comment by e3bo** [comment]
The badge is on there but it is the badge for my fork.

Sure I can make badges for the rest. I'll push that to this pull request in
a minute.

**Comment by e3bo** [comment]
To explain things a little more, I disabled actions on my fork so that they don't use up my quota of action resources. Maybe there should be a warning about that somewhere.

**Comment by mvevans89** [comment]
Ahh makes sense. I think the default on forks of this repo are that Actions are disabled, but I can add a note to the README to warn people to check just in case

**Pull request merged**
